// 사이드바 공통 스타일
export const sidebarStyles = {
  container: (isOpen, animationValues) => ({
    width: isOpen ? '240px' : '60px',
    height: '100vh',
    background: '#fff',
    borderRight: '1px solid #e5e7eb',
    boxShadow: '2px 0 8px rgba(0,0,0,0.06)',
    transition: `width ${animationValues.DURATION.SLOW} ${animationValues.EASE_OUT}`,
    display: 'flex',
    flexDirection: 'column',
    zIndex: 1000,
    overflow: 'hidden',
  }),
  header: {
    height: '54px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '12px',
    padding: '0 16px',
    borderBottom: '1px solid #e5e7eb',
    background: '#f8f9fc',
    overflow: 'hidden',
    flexShrink: 0,
  },
  toggleButton: (animationValues) => ({
    width: '32px',
    height: '32px',
    borderRadius: '6px',
    border: '1px solid #e3e6ef',
    background: '#fff',
    color: '#6C8EFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: `all ${animationValues.DURATION.FAST} ease`,
    outline: 'none',
  }),
  title: (isOpen, animationValues) => ({
    fontSize: '20px',
    fontWeight: '600',
    color: '#22336b',
    textAlign: 'left',
    opacity: isOpen ? 1 : 0,
    transform: isOpen ? 'translateX(0)' : 'translateX(-20px)',
    transition: `all ${animationValues.DURATION.NORMAL} ${animationValues.EASE_OUT}`,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    width: isOpen ? 'auto' : '0px',
    display: 'inline-block',
    minWidth: isOpen ? 'auto' : '0px',
  }),
  chapterList: {
    flex: 1,
    padding: '16px 0',
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  chapterButton: (isSelected, isOpen, animationValues) => ({
    width: '100%',
    height: '48px',
    padding: '0 16px',
    border: 'none',
    background: isSelected ? '#EEF2FF' : 'transparent',
    color: isSelected ? '#22336b' : '#6C8EFF',
    fontSize: '14px',
    fontWeight: isSelected ? '600' : '500',
    textAlign: 'left',
    cursor: 'pointer',
    transition: `all ${animationValues.DURATION.NORMAL} ${animationValues.EASE_OUT}`,
    borderLeft: isSelected ? '4px solid #6C8EFF' : '4px solid transparent',
    transform: isSelected ? 'translateX(4px)' : 'translateX(0)',
    boxShadow: isSelected ? '0 2px 8px rgba(108, 142, 255, 0.15)' : 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: isOpen ? 'flex-start' : 'center',
    position: 'relative',
    overflow: 'hidden',
  }),
  chapterNumber: (isSelected, animationValues) => ({
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    background: isSelected ? '#6C8EFF' : '#e3e6ef',
    color: isSelected ? '#fff' : '#6C8EFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '600',
    marginRight: '12px',
    transition: `all ${animationValues.DURATION.NORMAL} ease`,
    flexShrink: 0,
    minWidth: '24px',
    minHeight: '24px',
  }),
  chapterText: (isOpen, animationValues) => ({
    opacity: isOpen ? 1 : 0,
    transform: isOpen ? 'translateX(0)' : 'translateX(-30px)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    width: isOpen ? 'auto' : '0px',
    transition: `all ${animationValues.DURATION.NORMAL} ${animationValues.EASE_OUT}`,
    display: 'inline-block',
    minWidth: isOpen ? 'auto' : '0px',
    maxWidth: isOpen ? 'calc(100% - 36px)' : '0px',
  }),
};

// 상단바 공통 스타일
export const topBarStyles = {
  container: {
    width: '100%',
    background: '#fff',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
    zIndex: 10001,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingLeft: 16,
    paddingRight: 16,
    height: 54,
    flexWrap: 'nowrap',
    overflow: 'visible',
  },
  leftControls: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
    overflow: 'visible',
    flexWrap: 'nowrap',
  },
  rightControls: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
    marginRight: '20px',
  },
  closeButton: (animationValues) => ({
    height: 36,
    width: 36,
    borderRadius: 8,
    border: '1.5px solid #e3e6ef',
    background: '#fff',
    color: '#22336b',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: `all ${animationValues.DURATION.FAST} ease`,
    outline: 'none',
    fontSize: 14,
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
  }),
};

// 로딩/에러 컨테이너 스타일
export const containerStyles = {
  loading: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    color: '#6C8EFF',
  },
  error: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    color: '#ef4444',
    textAlign: 'center',
    padding: '20px',
  },
};
